"""Audio-centric multimodal task definitions (incl. audio generation)."""

from __future__ import annotations

from multimodal.tasks.contracts import TaskDefinition

AUDIO_TASK_DEFINITIONS: tuple[TaskDefinition, ...] = (
    TaskDefinition(
        name="audio_text_pair",
        family="audio",
        required_input_modalities=("audio", "text"),
        output_modalities=("embedding",),
        required_target_fields=("target_text",),
        evaluation_method="retrieval_or_contrastive",
        loss_key="contrastive",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("positive_id", "negative_ids"),
        supports_hard_negatives=True,
        description="Audio-text contrastive alignment.",
    ),
    TaskDefinition(
        name="speech_translation",
        family="audio",
        required_input_modalities=("audio",),
        output_modalities=("text", "audio"),
        required_target_fields=("target_text", "target_audio_path"),
        evaluation_method="bleu_audio_latency",
        loss_key="speech_translation",
        sample_source="external",
        maturity="beta",
        optional_annotation_fields=("speaker_segments", "prosody"),
        description="Translate source speech to target text and/or speech.",
    ),
    TaskDefinition(
        name="speech_reconstruction",
        family="audio",
        required_input_modalities=("audio",),
        output_modalities=("audio",),
        required_target_fields=("target_audio_path",),
        evaluation_method="audio_similarity",
        loss_key="audio_generation",
        sample_source="external",
        maturity="experimental",
        optional_annotation_fields=("target_text", "prosody"),
        description=(
            "Reconstruct or convert source audio (e.g. voice conversion, enhancement)."
        ),
    ),
    TaskDefinition(
        name="speech_transcription",
        family="audio",
        required_input_modalities=("audio",),
        output_modalities=("text",),
        required_target_fields=("target_text",),
        evaluation_method="cer_wer",
        loss_key="language_modeling",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("speaker_segments", "prosody"),
        description="Transcribe speech audio into text.",
    ),
    TaskDefinition(
        name="audio_summarization",
        family="audio",
        required_input_modalities=("audio", "text"),
        output_modalities=("text",),
        required_target_fields=("target_text",),
        evaluation_method="rouge_or_token_f1",
        loss_key="language_modeling",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("speaker_segments",),
        description="Summarize audio or transcript content.",
    ),
    TaskDefinition(
        name="audio_qa",
        family="audio",
        required_input_modalities=("audio", "text"),
        output_modalities=("text",),
        required_target_fields=("question", "target_text"),
        evaluation_method="exact_match_f1",
        loss_key="language_modeling",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=(
            "speaker_segments",
            "transcript_segments",
        ),
        description="Answer questions grounded in audio content.",
    ),
    TaskDefinition(
        name="background_sound_classification",
        family="audio",
        required_input_modalities=("audio",),
        output_modalities=("class",),
        required_target_fields=("background_noise_label",),
        evaluation_method="classification_f1",
        loss_key="classification",
        sample_source="external",
        maturity="experimental",
        description="Classify background sounds or acoustic scenes.",
    ),
    TaskDefinition(
        name="audio_emotion",
        family="audio",
        required_input_modalities=("audio", "text"),
        output_modalities=("class",),
        required_target_fields=("emotion_label",),
        evaluation_method="emotion_f1",
        loss_key="emotion",
        sample_source="external",
        maturity="beta",
        optional_annotation_fields=("arousal", "valence", "dominance"),
        sensitivity="sensitive",
        description="Classify emotion, tone, and affect from speech.",
    ),
    TaskDefinition(
        name="speaker_id",
        family="audio",
        required_input_modalities=("audio",),
        output_modalities=("class",),
        required_target_fields=("speaker_segments",),
        evaluation_method="speaker_accuracy",
        loss_key="speaker_contrastive",
        sample_source="external",
        maturity="disabled",
        optional_annotation_fields=("speaker_label",),
        sensitivity="biometric_identity",
        description="Learn speaker embeddings and speaker identities.",
    ),
    TaskDefinition(
        name="speaker_diarization",
        family="audio",
        required_input_modalities=("audio",),
        output_modalities=("json",),
        required_target_fields=("speaker_segments",),
        evaluation_method="diarization_error_rate",
        loss_key="diarization",
        sample_source="external",
        maturity="disabled",
        optional_annotation_fields=("overlapping_speech",),
        sensitivity="sensitive",
        description="Predict who speaks when, including overlaps.",
    ),
    TaskDefinition(
        name="speech_to_audio",
        family="audio",
        required_input_modalities=("text",),
        output_modalities=("audio",),
        required_target_fields=("target_audio_path",),
        evaluation_method="audio_token_accuracy",
        loss_key="audio_generation",
        sample_source="crawler_derived",
        maturity="experimental",
        optional_annotation_fields=("prosody",),
        description="Generate target audio from text or instructions.",
    ),
)
