"""Document-centric multimodal task definitions."""

from __future__ import annotations

from multimodal.tasks.contracts import TaskDefinition

DOCUMENT_TASK_DEFINITIONS: tuple[TaskDefinition, ...] = (
    TaskDefinition(
        name="document_text_pair",
        family="document",
        required_input_modalities=("document", "text"),
        output_modalities=("embedding",),
        required_target_fields=("target_text",),
        evaluation_method="retrieval_or_contrastive",
        loss_key="contrastive",
        sample_source="crawler_derived",
        maturity="stable",
        optional_annotation_fields=("positive_id", "negative_ids"),
        supports_hard_negatives=True,
        description="Document-text contrastive alignment.",
    ),
    TaskDefinition(
        name="pdf_text_pair",
        family="document",
        required_input_modalities=("document", "text"),
        output_modalities=("embedding",),
        required_target_fields=("target_text",),
        evaluation_method="retrieval_or_contrastive",
        loss_key="contrastive",
        sample_source="crawler_derived",
        maturity="stable",
        optional_annotation_fields=("positive_id", "negative_ids"),
        supports_hard_negatives=True,
        description="PDF-text contrastive alignment.",
    ),
    TaskDefinition(
        name="document_summarization",
        family="document",
        required_input_modalities=("document", "text"),
        output_modalities=("text",),
        required_target_fields=("target_text",),
        evaluation_method="rouge_or_token_f1",
        loss_key="language_modeling",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("layout_boxes",),
        description="Summarize a document using extracted text and layout.",
    ),
    TaskDefinition(
        name="document_comparison",
        family="document",
        required_input_modalities=("document", "text"),
        output_modalities=("text", "json", "class"),
        required_target_fields=("target_text",),
        evaluation_method="exact_match_f1",
        loss_key="language_modeling",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("positive_id", "negative_ids"),
        supports_hard_negatives=True,
        description="Compare documents or explain document-level differences.",
    ),
    TaskDefinition(
        name="table_extraction",
        family="document",
        required_input_modalities=("document", "text", "layout"),
        output_modalities=("json",),
        required_target_fields=("target_table_structure",),
        evaluation_method="table_structure_accuracy",
        loss_key="ocr_sequence",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("layout_boxes",),
        description="Extract table structure from documents or spreadsheets.",
    ),
    TaskDefinition(
        name="doc_qa",
        family="document",
        required_input_modalities=("document", "text"),
        output_modalities=("text",),
        required_target_fields=("question", "target_text"),
        evaluation_method="exact_match_f1",
        loss_key="language_modeling",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("layout_boxes",),
        description="Answer questions grounded in a document.",
    ),
    TaskDefinition(
        name="table_qa",
        family="table_spreadsheet",
        required_input_modalities=("document", "text"),
        output_modalities=("text",),
        required_target_fields=("question", "target_text"),
        evaluation_method="exact_match_f1",
        loss_key="language_modeling",
        sample_source="external",
        maturity="experimental",
        optional_annotation_fields=("target_table_structure", "layout_boxes"),
        description="Answer questions over table or spreadsheet data.",
    ),
    TaskDefinition(
        name="spreadsheet_analysis",
        family="table_spreadsheet",
        required_input_modalities=("document", "text"),
        output_modalities=("text", "json"),
        required_target_fields=("target_text",),
        evaluation_method="exact_match_f1",
        loss_key="language_modeling",
        sample_source="external",
        maturity="experimental",
        optional_annotation_fields=("target_table_structure",),
        description="Analyze spreadsheet-like records.",
    ),
    TaskDefinition(
        name="chart_generation",
        family="table_spreadsheet",
        required_input_modalities=("text",),
        output_modalities=("json",),
        required_target_fields=("chart_data",),
        evaluation_method="chart_numeric_accuracy",
        loss_key="chart_reasoning",
        sample_source="external",
        maturity="experimental",
        optional_annotation_fields=("target_table_structure",),
        description="Generate chart data from structured text or tables.",
    ),
    TaskDefinition(
        name="data_anomaly_detection",
        family="table_spreadsheet",
        required_input_modalities=("document", "text"),
        output_modalities=("class", "text"),
        required_target_fields=("target_text",),
        evaluation_method="classification_f1",
        loss_key="classification",
        sample_source="external",
        maturity="experimental",
        optional_annotation_fields=("target_table_structure",),
        description="Detect anomalies in table or spreadsheet data.",
    ),
    TaskDefinition(
        name="passage_retrieval",
        family="retrieval",
        required_input_modalities=("document", "text"),
        output_modalities=("class", "text"),
        required_target_fields=("positive_id", "negative_ids"),
        evaluation_method="retrieval_accuracy",
        loss_key="contrastive",
        sample_source="crawler_derived",
        maturity="beta",
        supports_hard_negatives=True,
        description="Retrieve document passages or chunks.",
    ),
    TaskDefinition(
        name="multifile_reasoning",
        family="multimodal_reasoning",
        required_input_modalities=("document", "text"),
        output_modalities=("text", "json"),
        required_target_fields=("target_text",),
        evaluation_method="exact_match_f1",
        loss_key="language_modeling",
        sample_source="external",
        maturity="experimental",
        optional_annotation_fields=("positive_id", "negative_ids"),
        description="Reason across multiple documents or files.",
    ),
)
