"""Image-centric multimodal task definitions (incl. image generation)."""

from __future__ import annotations

from multimodal.tasks.contracts import TaskDefinition

IMAGE_TASK_DEFINITIONS: tuple[TaskDefinition, ...] = (
    TaskDefinition(
        name="image_text_pair",
        family="image",
        required_input_modalities=("image", "text"),
        output_modalities=("embedding",),
        required_target_fields=("target_text",),
        evaluation_method="retrieval_or_contrastive",
        loss_key="contrastive",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("positive_id", "negative_ids"),
        supports_hard_negatives=True,
        description="Image-text contrastive alignment.",
    ),
    TaskDefinition(
        name="image_captioning",
        family="image",
        required_input_modalities=("image", "text"),
        output_modalities=("text",),
        required_target_fields=("target_text",),
        evaluation_method="rouge_or_token_f1",
        loss_key="language_modeling",
        sample_source="crawler_derived",
        maturity="experimental",
        optional_annotation_fields=("caption_source",),
        supports_hard_negatives=False,
        description="Generate a grounded natural-language caption for an image.",
    ),
    TaskDefinition(
        name="object_recognition",
        family="image",
        required_input_modalities=("image",),
        output_modalities=("json", "class"),
        required_target_fields=("object_boxes",),
        evaluation_method="visual_grounding_box_mse",
        loss_key="visual_grounding",
        sample_source="external",
        maturity="experimental",
        optional_annotation_fields=("geometry_annotations",),
        description="Recognize or ground objects in an image.",
    ),
    TaskDefinition(
        name="image_classification",
        family="image",
        required_input_modalities=("image",),
        output_modalities=("class",),
        required_target_fields=("label",),
        evaluation_method="classification_f1",
        loss_key="classification",
        sample_source="external",
        maturity="experimental",
        description="Classify an image using a concrete label.",
    ),
    TaskDefinition(
        name="vqa",
        family="image",
        required_input_modalities=("image", "text"),
        output_modalities=("text",),
        required_target_fields=("question", "target_text"),
        evaluation_method="vqa_accuracy",
        loss_key="language_modeling",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("object_boxes", "geometry_annotations"),
        supports_hard_negatives=True,
        description="Answer a natural-language question about an image.",
    ),
    TaskDefinition(
        name="ocr_parse",
        family="image",
        required_input_modalities=("image", "layout"),
        output_modalities=("text", "json"),
        required_target_fields=("target_text", "layout_boxes"),
        evaluation_method="cer_wer_layout",
        loss_key="ocr_sequence",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("target_table_structure", "form_fields"),
        description="Extract text and structured layout from documents.",
    ),
    TaskDefinition(
        name="ui_to_code",
        family="screen_ui",
        required_input_modalities=("image", "layout", "text"),
        output_modalities=("code",),
        required_target_fields=("instruction", "target_code"),
        evaluation_method="code_validity_render",
        loss_key="language_modeling",
        sample_source="external",
        maturity="experimental",
        optional_annotation_fields=("ui_elements",),
        description="Convert a UI sketch or screenshot into code.",
    ),
    TaskDefinition(
        name="screenshot_qa",
        family="screen_ui",
        required_input_modalities=("image", "text"),
        output_modalities=("text",),
        required_target_fields=("question", "target_text"),
        evaluation_method="exact_match_f1",
        loss_key="language_modeling",
        sample_source="external",
        maturity="experimental",
        optional_annotation_fields=("ui_elements", "layout_boxes"),
        description="Answer questions about a screenshot or screen state.",
    ),
    TaskDefinition(
        name="ui_error_diagnosis",
        family="screen_ui",
        required_input_modalities=("image", "text"),
        output_modalities=("text", "json"),
        required_target_fields=("target_text",),
        evaluation_method="exact_match_f1",
        loss_key="language_modeling",
        sample_source="external",
        maturity="experimental",
        optional_annotation_fields=("ui_elements", "layout_boxes"),
        description="Diagnose UI errors or explain screen-state issues.",
    ),
    TaskDefinition(
        name="accessibility_audit",
        family="screen_ui",
        required_input_modalities=("image", "layout", "text"),
        output_modalities=("text", "json"),
        required_target_fields=("target_text",),
        evaluation_method="exact_match_f1",
        loss_key="language_modeling",
        sample_source="external",
        maturity="experimental",
        optional_annotation_fields=("ui_elements",),
        description="Audit UI accessibility from screenshot and structure.",
    ),
    TaskDefinition(
        name="screen_to_steps",
        family="screen_ui",
        required_input_modalities=("image", "text"),
        output_modalities=("text", "json"),
        required_target_fields=("target_text",),
        evaluation_method="exact_match_f1",
        loss_key="language_modeling",
        sample_source="external",
        maturity="experimental",
        optional_annotation_fields=("ui_elements",),
        description="Convert a screen state into user-facing steps.",
    ),
    TaskDefinition(
        name="chart_qa",
        family="image",
        required_input_modalities=("image", "text"),
        output_modalities=("text", "json"),
        required_target_fields=("question", "target_text", "chart_data"),
        evaluation_method="chart_numeric_accuracy",
        loss_key="chart_reasoning",
        sample_source="external",
        maturity="experimental",
        optional_annotation_fields=("object_boxes",),
        description="Answer questions about charts and plots.",
    ),
    TaskDefinition(
        name="visual_math",
        family="image",
        required_input_modalities=("image",),
        output_modalities=("text",),
        required_target_fields=("math_expression", "math_solution"),
        evaluation_method="math_equivalence",
        loss_key="math_reasoning",
        sample_source="external",
        maturity="experimental",
        optional_annotation_fields=("layout_boxes",),
        description="Parse and solve visual or handwritten math.",
    ),
    TaskDefinition(
        name="meme_explanation",
        family="image",
        required_input_modalities=("image", "text"),
        output_modalities=("text",),
        required_target_fields=("humor_explanation",),
        evaluation_method="human_or_semantic_rubric",
        loss_key="language_modeling",
        sample_source="external",
        maturity="experimental",
        optional_annotation_fields=("layout_boxes",),
        description="Explain humor, visual context, and references in memes.",
    ),
    TaskDefinition(
        name="text_to_image",
        family="image",
        required_input_modalities=("text",),
        output_modalities=("image",),
        required_target_fields=("instruction", "target_image_path"),
        evaluation_method="prompt_following",
        loss_key="image_generation",
        sample_source="external",
        maturity="disabled",
        optional_annotation_fields=("chart_data", "watermark_metadata"),
        description="Generate an image from a prompt.",
    ),
    TaskDefinition(
        name="image_editing",
        family="image",
        required_input_modalities=("image", "text", "mask"),
        output_modalities=("image",),
        required_target_fields=(
            "instruction",
            "source_image_path",
            "target_image_path",
        ),
        evaluation_method="edit_consistency",
        loss_key="image_editing",
        sample_source="external",
        maturity="disabled",
        optional_annotation_fields=("edit_mask_path",),
        description="Edit an image from an instruction and optional mask.",
    ),
)
