"""Text-centric multimodal task definitions."""

from __future__ import annotations

from multimodal.tasks.contracts import TaskDefinition

TEXT_TASK_DEFINITIONS: tuple[TaskDefinition, ...] = (
    TaskDefinition(
        name="representation",
        family="text",
        required_input_modalities=("text",),
        output_modalities=("class",),
        required_target_fields=(),
        evaluation_method="embedding_quality",
        loss_key="contrastive",
        sample_source="self_supervised",
        maturity="stable",
        optional_annotation_fields=("positive_id", "negative_ids"),
        supports_hard_negatives=True,
        description="Fallback encoder-fusion representation learning.",
    ),
    TaskDefinition(
        name="text_pretrain",
        family="text",
        required_input_modalities=("text",),
        output_modalities=("text",),
        required_target_fields=(),
        evaluation_method="masked_language_modeling",
        loss_key="text_mlm",
        sample_source="self_supervised",
        maturity="stable",
        description="Self-supervised text reconstruction/pretraining.",
    ),
    TaskDefinition(
        name="causal_text_pretrain",
        family="text",
        required_input_modalities=("text",),
        output_modalities=("text",),
        required_target_fields=(),
        evaluation_method="causal_language_modeling",
        loss_key="language_modeling",
        sample_source="self_supervised",
        maturity="experimental",
        description="Autoregressive next-token pretraining on approved text.",
    ),
    TaskDefinition(
        name="instruction_following",
        family="text",
        required_input_modalities=("text",),
        output_modalities=("text",),
        required_target_fields=("instruction", "target_text"),
        evaluation_method="exact_match_f1",
        loss_key="language_modeling",
        sample_source="external",
        maturity="beta",
        description="Follow a natural-language instruction with a text answer.",
    ),
    TaskDefinition(
        name="summarization",
        family="text",
        required_input_modalities=("text",),
        output_modalities=("text",),
        required_target_fields=("target_text",),
        evaluation_method="rouge_or_token_f1",
        loss_key="language_modeling",
        sample_source="crawler_derived",
        maturity="beta",
        description="Summarize text into a shorter target.",
    ),
    TaskDefinition(
        name="translation",
        family="text",
        required_input_modalities=("text",),
        output_modalities=("text",),
        required_target_fields=("target_text",),
        evaluation_method="bleu",
        loss_key="language_modeling",
        sample_source="external",
        maturity="experimental",
        description="Translate text into another language.",
    ),
    TaskDefinition(
        name="classification",
        family="text",
        required_input_modalities=("text",),
        output_modalities=("class",),
        required_target_fields=("label",),
        evaluation_method="classification_f1",
        loss_key="classification",
        sample_source="external",
        maturity="stable",
        description="Classify text using a concrete label.",
    ),
    TaskDefinition(
        name="information_extraction",
        family="text",
        required_input_modalities=("text",),
        output_modalities=("text", "json"),
        required_target_fields=("target_text",),
        evaluation_method="exact_match_f1",
        loss_key="language_modeling",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("form_fields", "target_table_structure"),
        description="Extract structured facts or metadata from text.",
    ),
    TaskDefinition(
        name="semantic_search",
        family="retrieval",
        required_input_modalities=("text",),
        output_modalities=("class", "text"),
        required_target_fields=("positive_id", "negative_ids"),
        evaluation_method="retrieval_accuracy",
        loss_key="contrastive",
        sample_source="external",
        maturity="beta",
        supports_hard_negatives=True,
        description="Retrieve semantically related text passages.",
    ),
    TaskDefinition(
        name="duplicate_detection",
        family="retrieval",
        required_input_modalities=("text",),
        output_modalities=("class",),
        required_target_fields=("label",),
        evaluation_method="classification_f1",
        loss_key="classification",
        sample_source="external",
        maturity="experimental",
        description="Detect duplicate or near-duplicate content.",
    ),
    TaskDefinition(
        name="multimodal_retrieval",
        family="cross_modal",
        required_input_modalities=("text",),
        evidence_modalities=(
            "document",
            "image",
            "audio",
            "video",
        ),
        min_evidence_modalities=1,
        output_modalities=("embedding",),
        required_target_fields=("positive_id", "negative_ids"),
        evaluation_method="retrieval_accuracy",
        loss_key="contrastive",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("image", "audio", "video", "document"),
        supports_hard_negatives=True,
        description="Retrieve aligned examples across modalities.",
    ),
    TaskDefinition(
        name="cross_modal_consistency",
        family="cross_modal",
        required_input_modalities=("text",),
        evidence_modalities=(
            "document",
            "image",
            "audio",
            "video",
        ),
        min_evidence_modalities=1,
        output_modalities=("class",),
        required_target_fields=("positive_id", "negative_ids"),
        evaluation_method="retrieval_accuracy",
        loss_key="contrastive",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("label",),
        supports_hard_negatives=True,
        description=(
            "Score aligned evidence above explicit cross-modal hard negatives."
        ),
    ),
)
