"""Video-centric multimodal task definitions (incl. video generation)."""

from __future__ import annotations

from multimodal.tasks.contracts import TaskDefinition

VIDEO_TASK_DEFINITIONS: tuple[TaskDefinition, ...] = (
    TaskDefinition(
        name="video_text_pair",
        family="video",
        required_input_modalities=("video", "text"),
        output_modalities=("embedding",),
        required_target_fields=("target_text",),
        evaluation_method="retrieval_or_contrastive",
        loss_key="contrastive",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("positive_id", "negative_ids"),
        supports_hard_negatives=True,
        description="Video-text contrastive alignment.",
    ),
    TaskDefinition(
        name="video_captioning",
        family="video",
        required_input_modalities=("video",),
        output_modalities=("text",),
        required_target_fields=("target_text",),
        evaluation_method="rouge_or_token_f1",
        loss_key="language_modeling",
        sample_source="crawler_derived",
        maturity="experimental",
        optional_annotation_fields=(
            "scene_graph",
            "video_caption_source",
            "video_segment_start_seconds",
            "video_segment_end_seconds",
        ),
        description="Caption video content.",
    ),
    TaskDefinition(
        name="video_qa",
        family="video",
        required_input_modalities=("video", "text"),
        output_modalities=("text",),
        required_target_fields=("question", "target_text"),
        evaluation_method="exact_match_f1",
        loss_key="language_modeling",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("scene_graph",),
        description="Answer questions grounded in a video.",
    ),
    TaskDefinition(
        name="scene_understanding",
        family="video",
        required_input_modalities=("video",),
        output_modalities=("json",),
        required_target_fields=("scene_graph",),
        evaluation_method="scene_graph_overlap",
        loss_key="language_modeling",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("object_boxes",),
        description="Predict structured scene information from video.",
    ),
    TaskDefinition(
        name="action_recognition",
        family="video",
        required_input_modalities=("video",),
        output_modalities=("class",),
        required_target_fields=("label",),
        evaluation_method="classification_f1",
        loss_key="classification",
        sample_source="external",
        maturity="beta",
        description="Classify actions or activities in video.",
    ),
    TaskDefinition(
        name="video_summarization",
        family="video",
        required_input_modalities=("video", "text"),
        output_modalities=("text",),
        required_target_fields=("target_text",),
        evaluation_method="rouge_or_token_f1",
        loss_key="language_modeling",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("scene_graph",),
        description="Summarize video content from transcripts or keyframes.",
    ),
    TaskDefinition(
        name="scene_retrieval",
        family="retrieval",
        required_input_modalities=("video", "text"),
        output_modalities=("class", "text"),
        required_target_fields=("positive_id", "negative_ids"),
        evaluation_method="retrieval_accuracy",
        loss_key="contrastive",
        sample_source="crawler_derived",
        maturity="beta",
        optional_annotation_fields=("scene_graph",),
        supports_hard_negatives=True,
        description="Retrieve video scenes by text or scene metadata.",
    ),
    TaskDefinition(
        name="text_to_video",
        family="video",
        required_input_modalities=("text",),
        output_modalities=("video",),
        required_target_fields=("instruction", "target_video_path"),
        evaluation_method="video_prompt_following",
        loss_key="video_generation",
        sample_source="external",
        maturity="disabled",
        optional_annotation_fields=("scene_graph",),
        description="Generate a video from a prompt.",
    ),
    TaskDefinition(
        name="video_editing",
        family="video",
        required_input_modalities=("video", "text", "mask"),
        output_modalities=("video",),
        required_target_fields=("instruction", "target_video_path"),
        evaluation_method="video_edit_consistency",
        loss_key="video_generation",
        sample_source="external",
        maturity="disabled",
        optional_annotation_fields=("scene_graph",),
        description="Edit a video from an instruction and optional mask.",
    ),
)
